// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1X1HKaFODp_2AmOlrdNFQIsRFQZe5fjw',
    appId: '1:181700544826:web:ee381eae0b848dc28de803',
    messagingSenderId: '181700544826',
    projectId: 'newproject-618b5',
    authDomain: 'newproject-618b5.firebaseapp.com',
    storageBucket: 'newproject-618b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlmlF3uoDMn9GuOwHfyBgOqbXPt-AeMNY',
    appId: '1:181700544826:android:6e74b1dad7036c058de803',
    messagingSenderId: '181700544826',
    projectId: 'newproject-618b5',
    storageBucket: 'newproject-618b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUQTcM1bTlkR17tm6BCWeWNKCIY-HxPu8',
    appId: '1:181700544826:ios:7800d4979974eb268de803',
    messagingSenderId: '181700544826',
    projectId: 'newproject-618b5',
    storageBucket: 'newproject-618b5.appspot.com',
    iosBundleId: 'com.example.taskAuthWithFirebasesAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUQTcM1bTlkR17tm6BCWeWNKCIY-HxPu8',
    appId: '1:181700544826:ios:77905c9263bef59d8de803',
    messagingSenderId: '181700544826',
    projectId: 'newproject-618b5',
    storageBucket: 'newproject-618b5.appspot.com',
    iosBundleId: 'com.example.taskAuthWithFirebasesAuth.RunnerTests',
  );
}
